spring:
  application:
    name: BookShoppingCart

  #Database Config
  datasource:
    url: jdbc:h2:mem:bookstoredb;MODE=MSSQLServer;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Alterado para recriar a base de dados a cada início
    defer-datasource-initialization: true # Adicionado para garantir que o schema seja criado antes do data.sql

  sql:
    init:
      mode: always # Ativa a execução de data.sql e schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

#Swagger Config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

#Export Config
cart:
  export:
    path: C:\\temp